### ISSUE TITLE
Can't enable when using slimefun 820 version

### ISSUE THREAD

**Issue by xMikux** [GallowsDove/FoxyMachines#12]
## Description (Required)

Can't enable the addon when using Slimefun DEV - 820.

## Steps to reproduce the Issue (Required)
1. Install Slimefun DEV - 820 & FoxyMachines DEV 12
2. Have error and disable the addon!

## Expected behavior (Required)
No error, and enable the addon.

## Server Log / Error Report

https://pastebin.com/0B3zbjBm

## Environment (Required)

![image](https://user-images.githubusercontent.com/26039249/108828525-ebeaa380-7601-11eb-845f-b35aa77b1f76.png)

 - Minecraft Version: git-Paper-487 (MC: 1.16.5)
 - CS-CoreLib Version:
 - Slimefun Version: DEV - 820 (git 338fe0f8)
 - Plugin Version: vDEV - 12 (git 869a3081)

**Comment by 100petr** [comment]
The plugin also does not work for me on the new sf version https://pastebin.com/uHAuT4pZ chunk loader I have turned off in items.yml
![image](https://user-images.githubusercontent.com/29830635/108945303-aad3ad00-765c-11eb-999d-96f3fdc261a3.png)

**Comment by GallowsDove** [comment]
Should be fixed in latest version
