### ISSUE TITLE
plugin doesn't load. block handler error 

### ISSUE THREAD

**Issue by Boomer-1** [GallowsDove/FoxyMachines#13]
## Description (Required)

i caught this in the console. I am not a programmer so I can't tell you what caused it.

## Steps to reproduce the Issue (Required)

load a server

## Server Log / Error Report

https://pastebin.com/Ax2fTzWQ

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version: Dev 822
 - Plugin Version: Dev 12

**Comment by GallowsDove** [comment]
Should be fixed in latest version
