### ISSUE TITLE
Boosted power rails may be too fast for comparator to get a signal from activator rail

### ISSUE THREAD

**Issue by Boomer-1** [GallowsDove/FoxyMachines#15]
## Description (Required)

when running a hopper minecart on a length of boosted power rails, as the minecart reaches an activator rail, the minecart goes too fast it seems for the comparator to get the signal consistently. 

## Steps to reproduce the Issue (Required)

i placed down about 50 boosted power rails in a row, with an activator rail at one end.
place down a hopper minecart with at least 1 item in it.
have it run over an activator rail with a comparator checking for a signal from the minecart
most times it won't detect it.

## Expected behavior (Required)

the comparator to be able to read the signal from the minecart.

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed
 - Slimefun Version: 822
 - Plugin Version: 17

**Comment by GallowsDove** [comment]
This will most probably not be addressed, as it can be slowed down using other rails. It's a good thing to note tho, I don't see it as a reason to slow them down yet tho
