### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by bobhenl** [GallowsDove/FoxyMachines#16]
Hi, just question, could you add support for Java 8 again?

**Comment by GallowsDove** [comment]
I could, but I see no good reason to. It just makes my job harder and Java is backwards compatible, so you should be able to update to latest Java without any issues.

**Comment by GallowsDove** [comment]
Since Paper will be dropping java 8 support with the release of Minecraft 1.17, the support won't be re-added.
