### ISSUE TITLE
plugin can't load

### ISSUE THREAD

**Issue by 4o4E** [GallowsDove/FoxyMachines#19]
![TAAJNPW}V(XZ2064$00(%WA](https://user-images.githubusercontent.com/58851040/111296001-f5a67a80-8686-11eb-9fc4-9b450c5991b9.png)
![image](https://user-images.githubusercontent.com/58851040/111295870-d6a7e880-8686-11eb-848e-77c0f9c68485.png)

I try OracleJDK(8u281) and OpenJDK(8u282), but it did't work.
Should I switch to another version of Java？

**Comment by GallowsDove** [comment]
You need to be using at least java version 11, whether it's OpenJDK  or Oracle. As you can see in /sf versions, you are on version 8.

**Comment by GallowsDove** [comment]
Feel free to download latest version (Java 15) either from Oracle or OpenJDK, as Java is backwards compatible, so updating shouldn't break anything

**Comment by 4o4E** [comment]
OK, thank you for your answer

**Comment by 4o4E** [comment]
![_UZFM(2NU3EA U)BN5VDP@Y](https://user-images.githubusercontent.com/58851040/111789799-81750c80-88fc-11eb-9354-1784abb67dcb.png)
![) 6}U 2Z1T@~ $4GP3%Z2ZR](https://user-images.githubusercontent.com/58851040/111789807-82a63980-88fc-11eb-8f71-7dd5a12a36d8.png)
![P6G{40J(M%0Q304)8GU$Y3J](https://user-images.githubusercontent.com/58851040/111789812-83d76680-88fc-11eb-8581-1b6af247b3bd.png)
I use OpenJDK15
![image](https://user-images.githubusercontent.com/58851040/111789968-acf7f700-88fc-11eb-9359-75dbc9610b4b.png)

**Comment by GallowsDove** [comment]
Please update to latest version first, you still have 37

**Comment by GallowsDove** [comment]
I'll take a look at it in a while tho

**Comment by GallowsDove** [comment]
Also please create a new issue as this is unrelated
