### ISSUE TITLE
The rail based items disappear if break out the block under the rail

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#22]
## Description (Required)

The rail based items disappear if break out the block under the rail.

## Steps to reproduce the Issue (Required)

https://www.youtube.com/watch?v=jaPAZ2vj2sQ

## Expected behavior (Required)

The rail based items no disappear if break out the block under the rail.

## Server Log / Error Report

None

## Environment (Required)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 861 (git 73b5ef8b)
Metrics-Module #21
Java 11

Installed Addons: (3)
  InfinityExpansion vDEV - 98 (git 4cf7e322)
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 88 (git c06f0e25)

**Comment by GallowsDove** [comment]
While this is still true, it's a Slimefun issue, not a Foxy issue. I believe they are already aware of it, so there is nothing for me to do.
