### ISSUE TITLE
Add a config option for Custom Mobs

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#23]
## Description (Required)

The MobTicker uses lot of server CPU.

## Steps to reproduce the Issue (Required)

1. Use FoxyMachines on the large server.

![Screenshot 2021-04-01 225810](https://user-images.githubusercontent.com/8324198/113353654-4b914880-933e-11eb-9c9f-39db18c75dcc.jpg)

## Expected behavior (Required)

MobTicker task no uses lot of server CPU or add config option to disable this.

## Server Log / Error Report

none

## Environment (Required)

Tuinity git-Tuinity-"94f025a" (MC: 1.16.5)
Slimefun DEV - 864 (git 82366191)
Metrics-Module #21
Java 11

Installed Addons: (14)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 25 (git 209f9078)
  PomaExpansion vDEV - 15 (git f4bb6859)
  SlimefunFix v3.0
  FoxyMachines vDEV - 42 (git ae8d8aba)
  EcoPower vDEV - 3 (git 18ba903d)
  DynaTech vDEV - 92 (git 52437eea)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 32 (git e108f086)
  InfinityExpansion vDEV - 100 (git 65892de0)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 15 (git 6586cb3f)
  LiteXpansion vDEV - 138 (git 004e3c61)
  FluffyMachines vDEV - 72 (git f2ad968f)

**Comment by GallowsDove** [comment]
I'm planning on adding a config option to disable custom mobs overall and use different recipes in that case. How big is this server?

**Comment by andris155** [comment]
Playing usually 30-40 players daily.

**Comment by andris155** [comment]
Thanks.
