### ISSUE TITLE
Bug Rune Unbreakable

### ISSUE THREAD

**Issue by ArrozElMank** [GallowsDove/FoxyMachines#24]
## Description (Required)
I follow the instructions given by the rune and it doesn't work

## Steps to reproduce the Issue (Required)
https://www.youtube.com/watch?v=ddD29m-8Qa0

## Expected behavior (Required)
make it unbreakable

## Server Log / Error Report
Nothing

## Environment (Required)
https://imgur.com/B0wPjqp

**Comment by GallowsDove** [comment]
You need to throw the rune on an item, you did it in the wrong order
