### ISSUE TITLE
Plugin error when server stop

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#25]
## Description (Required)

Plugin error when server stop.

## Steps to reproduce the Issue (Required)

Sometimes writes plugin this error when server stop.

## Expected behavior (Required)

No plugin error when server stop.

## Server Log / Error Report

https://pastebin.com/AWcBF0hY

## Environment (Required)

Tuinity git-Tuinity-"d5261ad" (MC: 1.16.5)
Slimefun DEV - 878 (git 485dec74)
Metrics-Module #21
Java 11

Installed Addons: (14)
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  PomaExpansion v1.3.1
  SlimefunFix v3.0
  FoxyMachines vDEV - 44 (git d2d14cd8)
  EcoPower vDEV - 3 (git 18ba903d)
  DynaTech vDEV - 97 (git e62bcb6b)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  InfinityExpansion vDEV - 100 (git 65892de0)
  RestrictedCreative v2.4.8
  SFCalc vDEV - 20 (git 29ba88c6)
  LiteXpansion vDEV - 145 (git 4c36f4f9)
  FluffyMachines vDEV - 75 (git 10ca2094)

**Comment by GallowsDove** [comment]
Do you have custom mobs disabled?

**Comment by andris155** [comment]
Yes I disabled.

**Comment by GallowsDove** [comment]
Should be fixed in latest, please reopen if necessary
