### ISSUE TITLE
too powerful again

### ISSUE THREAD

**Issue by RIPISDRAD** [GallowsDove/FoxyMachines#28]
emmm?

**Comment by RIPISDRAD** [comment]
ok leaving a new one pixi is too powerful still 5 straight attack u are dead
and what is the prize really strength and healthboos for at least 5 min isnt a reward for that kinda hard thing
btw this error happens i will send the full log now at the end 
and that damn headless horse would not die but with exxcavator(foxy machine)
and i even upgrade it and it pissed me off so much still was a pain to kill it and i was usuing every power someone possibly got
![2021-05-22_14 24 56](https://user-images.githubusercontent.com/76468672/119222678-bffc9280-bb0a-11eb-9938-172d2ab83c98.png)
[Uploading latest.log…]()

**Comment by GallowsDove** [comment]
As I've stated before, it's probably a *plugin incompability* First of all could you please submit your plugin list? Also there is currently an option to disable the bosses in config.

**Comment by GallowsDove** [comment]
Also the log doesn't seem to load, could you please use something like pastebin?

**Comment by RIPISDRAD** [comment]
[latest.log](https://github.com/GallowsDove/FoxyMachines/files/6526213/latest.log)

**Comment by RIPISDRAD** [comment]
u can see all the possible things in there nothing to change the behavier of mobs or anything just a nice freaky server made by me
the other mobs are as intended
it probably sfs addon which is messing with these
btw thanks for ur patience
