### ISSUE TITLE
Too Powerful

### ISSUE THREAD

**Issue by EarthCraftOfficial** [GallowsDove/FoxyMachines#29]
The Vex is pretty powerful but I can beat it. Headless horseman is OP and I don't even know how to kill it

**Comment by GallowsDove** [comment]
Are you using the best gear? Please look at the other issue about this and provide as much information as possible. As stated previously, it's most probably a plugin incompability, so it'd really help to see your plugin list so that I can recreate it and fix it

**Comment by GallowsDove** [comment]
No correspondence from poster
