### ISSUE TITLE
Ghost blocks in residence

### ISSUE THREAD

**Issue by 100petr** [GallowsDove/FoxyMachines#30]
## Description (Required)

Ghost blocks can be placed / destroyed in the residence even though I do not have permission
I tried it in the region from worldguard, there it works properly, can there be a problem in the residence?
## Steps to reproduce the Issue (Required)

Place/destroy a ghost block in a foreign residence
The block is placed/destroyed
## Expected behavior (Required)

Ghost blocks will not be built in an unauthorized residence
## Server Log / Error Report

N/A
## Environment (Required)

 - Minecraft Version: Purpur 1.16.5
 - Slimefun Version: DEV - 930 
 - Plugin Version: DEV - 45
 - Residence Version: 4.9.3.10

**Comment by GallowsDove** [comment]
This would require Residences to support Slimefun's Protection Manager, otherwise I can't fix this without unwanted consequences.

**Comment by 100petr** [comment]
residence somehow supports slimefun. Storage and barrels from addons can't be opened by foreign players, but I'll open the issue tomorrow at the github residence
![image](https://user-images.githubusercontent.com/29830635/122685551-52787a80-d20c-11eb-9498-309320365e9a.png)

**Comment by GallowsDove** [comment]
The problem is that I could run a simulated BlockPlace Event, but I would like to avoid that since I'm not really placing a block and that could mess with other plugins

**Comment by 100petr** [comment]
I have created an issue now so that I will not forget it later 
But I have a feeling that when this was added https://github.com/GallowsDove/FoxyMachines/issues/21 the problem did not exist

**Comment by FanYueee** [comment]
The most reported method of support on this page, not sure if this helps.
https://github.com/Slimefun/Slimefun4/wiki/Protection-plugins

**Comment by 100petr** [comment]
I close it because what you wrote is a residence problem
