### ISSUE TITLE
An internal error occurred while attempting to perform this command whilst trying to run commands and not all foxy machines registering in slimefun guide

### ISSUE THREAD

**Issue by KaiserTheGamer** [GallowsDove/FoxyMachines#31]
## Description (Required)
Some aspects of this plugin are not loaded in the slimefun guide and any attempts to run commands related to the addon spit internal errors

## Steps to reproduce the Issue (Required)
Install slimefun, install Foxymachines, then load both of them. 

## Expected behavior (Required)
I expected there to be all available categories for the addon and for the commands to work.

## Server Log / Error Report
https://pastebin.com/XZeqF8Ku

## Environment (Required)
Paper: git-paper-705 (MC: 1.16.5)
Slimefun DEV - 930 (git 0224f94e)
Metrics- Module #22 
&cJava 11

Installed Addons: (3)
&cFoxyMachines &4vDEV - 45 (git ce4f8193)
&aMobCapturer &2vDEV - 15 (git a42c9e0c)
&aExoticGarden &2vDEV - 76 (git d148a362)

**Comment by GallowsDove** [comment]
Fixed in latest version
