### ISSUE TITLE
Asynchronous Chunk getEntities call! console flood on 1.17

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#32]
## Description (Required)

Asynchronous Chunk getEntities call! console flood on 1.17

## Steps to reproduce the Issue (Required)

Run plugin on 1.17 Paper.

## Expected behavior (Required)

No Asynchronous Chunk getEntities call! console flood on 1.17.

## Server Log / Error Report

https://pastebin.com/3E7gJepf

## Environment (Required)

Paper git-Paper-"ed5100f" (MC: 1.17)
Slimefun DEV - 938 (git 68f8a360)
Metrics-Module #25
Java 16

Installed Addons: (14)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  ExtraTools vDEV - 28 (git 58488a2e)
  PomaExpansion v1.3.1
  SlimefunFix v3.0
  FoxyMachines vDEV - 45 (git ce4f8193)
  EcoPower vDEV - 4 (git 2a08d31d)
  DynaTech vDEV - 114 (git 7f570d22)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  CMILib v1.0.2.1
  RestrictedCreative v2.5.1
  SFCalc vDEV - 26 (git d1b9ad01)
  LiteXpansion vDEV - 152 (git daa388b9)
  FluffyMachines vDEV - 84 (git cf78f53a)

**Comment by GallowsDove** [comment]
Fixed in latest version
