### ISSUE TITLE
Asynchronous Chunk getEntities call! console error on 1.17

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#33]
## Description (Required)

Asynchronous Chunk getEntities call! console error on 1.17

## Steps to reproduce the Issue (Required)

Run plugin on 1.17 Paper.

## Expected behavior (Required)

No Asynchronous Chunk getEntities call! console error on 1.17.

## Server Log / Error Report

https://pastebin.com/AsWKYGuZ

## Environment (Required)

Paper git-Paper-"ed5100f" (MC: 1.17)
Slimefun DEV - 938 (git 68f8a360)
Metrics-Module #25
Java 16

[11:19:17 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-"22280c5" (MC: 1.17)
Slimefun DEV - 939 (git 57f7553f)
Metrics-Module #25
Java 16

Installed Addons: (3)
  RestrictedCreative v2.5.1
  SlimefunFix v3.1
  FoxyMachines vDEV - 45 (git ce4f8193)

**Comment by 100petr** [comment]
How did you solve it? I have the same problem. #36

**Comment by andris155** [comment]
The developer fixed this in the latest version.
