### ISSUE TITLE
Error occurred while disabling FoxyMachines if disabled custom-mobs

### ISSUE THREAD

**Issue by andris155** [GallowsDove/FoxyMachines#35]
## Description (Required)

Error occurred while disabling FoxyMachines if disabled custom-mobs on the config.

## Steps to reproduce the Issue (Required)

1. Disable custom-mobs on the config.
2. Stop server.

## Expected behavior (Required)

No Error occurred while disabling FoxyMachines if disabled custom-mobs.

## Server Log / Error Report

https://pastebin.com/RMevhMf1

## Environment (Required)

[11:19:17 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-"22280c5" (MC: 1.17)
Slimefun DEV - 939 (git 57f7553f)
Metrics-Module #25
Java 16

[23:12:39 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-46 (MC: 1.17)
Slimefun DEV - 939 (git 57f7553f)
Metrics-Module #25
Java 16

Installed Addons: (14)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  ExtraTools vDEV - 28 (git 58488a2e)
  PomaExpansion v1.3.1
  SlimefunFix v3.1
  FoxyMachines vDEV - 47 (git 62fc841)
  DynaTech vDEV - 114 (git 7f570d22)
  EcoPower vDEV - 4 (git 2a08d31d)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  CMILib v1.0.2.3
  RestrictedCreative v2.5.1
  SFCalc vDEV - 26 (git d1b9ad01)
  LiteXpansion vDEV - 152 (git daa388b9)
  FluffyMachines vDEV - 85 (git 037a45b8)

**Comment by GallowsDove** [comment]
Fixed in latest, dowload currently only in Slimefun Addon Community Discord
