### ISSUE TITLE
error after updating to 1.17

### ISSUE THREAD

**Issue by 100petr** [GallowsDove/FoxyMachines#36]
## Description (Required)

error after updating to 1.17
## Steps to reproduce the Issue (Required)

Start server
## Expected behavior (Required)

There will be no errors
## Server Log / Error Report

https://pastebin.com/JBRC65aH
## Environment (Required)

 - Minecraft Version: purpur 1.17
 - Slimefun Version: DEV 942
 - Plugin Version: DEV 45

**Comment by GallowsDove** [comment]
Dev45 is not supported anymore, there is a new build on Slimefun Addon Community discord server. New build will come here as well as soon as the build server is updated.
