### ISSUE TITLE
unbreakable rune is not working

### ISSUE THREAD

**Issue by dhfirmino** [GallowsDove/FoxyMachines#37]
Description
unbreakable rune is not working, I drop the rune first, and it doesn't work.

Steps to reproduce the Issue
https://youtu.be/NF59yG9XoyI

Expected behavior
Item Should Become Unbreakable

Server Log / Error Report
none

Environment
Purpur git-Purpur-1171 (MC: 1.16.5)
Slimefun DEV - 950 (git 8c0ef8a9)
Metrics-Module #25
Java 16

Installed Addons: (31)
  ExtraTools vDEV - 28 (git 58488a2e)
  FoxyMachines vDEV - 49 (git 7654621f)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 44 (git 92333f39)
  SimpleMaterialGenerators vDEV - 6 (git 2083e132)
  DynaTech vDEV - 131 (git 64e0f7b5)
  ExtraGear vDEV - 12 (git 4570ea2c)
  InfinityExpansion vDEV - 115 (git a303bf48)
  SFCalc vDEV - 27 (git 4228476d)
  IllegalStack v2.2.2a
  EMC2 vDEV - 7 (git ec936209)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 19 (git 69930ef7)
  SlimeTinker vDEV - 20 (git 609a3c97)
  ColoredEnderChests vDEV - 22 (git 7c92625c)
  TranscEndence vDEV - 34 (git eece87db)
  FluffyMachines vDEV - 87 (git 2a086751)
  ChestTerminal vDEV - 43 (git 3096bab5)
  DyedBackpacks vDEV - 16 (git 20d28ccc)
  SoundMuffler vDEV - 21 (git 3206933b)
  AlchimiaVitae vDEV - 6 (git ed96769e)
  SlimefunWarfare vDEV - 46 (git 485bb330)
  Residence v4.9.3.5
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  ExoticGarden vDEV - 76 (git d148a362)
  Liquid vDEV - 12 (git b7a6c543)
  LiteXpansion vDEV - 153 (git a9a97232)
  SimpleUtils vDEV - 10 (git c619e27b)
  SimpleStorage vDEV - 5 (git 4f785adc)

**Comment by SolaceAndKairos** [comment]
This happens to me all the time, it's on and off and I'm never sure why it happens.
One time, it was the claims plugin not letting lightning strike or something ?
But all the others times, not sure.

**Comment by Disclosd** [comment]
It's the SLimefunWarefare Addon that's causing it I think or atleast it was in my server
