### ISSUE TITLE
Boss spawn egg in offhand destroys mainhand item after right clicking.

### ISSUE THREAD

**Issue by redstonepowder** [GallowsDove/FoxyMachines#38]
## Description:
With the Pixie Queen spawn egg in the offhand, right clicking will result in the mainhand item stack reduced by one (Or removed in the case of tools and/or armor), the boss itself being spawned, and the spawn egg still remaining in the offhand untouched.
Same conditions as above, except with nothing in the mainhand, will still spawn the boss and the spawn egg still remains.
The only exception seems to be with placeable items in the mainhand, such as potatoes or blocks, where nothing occurs while rightclicking.
The issue here is that, players will be able to use a spawn egg indefinitely, without any repercussions, along with unsuspecting players potentially losing valuable items such as a strong sword or a backpack.

## Steps to reproduce the Issue:
https://youtu.be/t8wK82WGEYk

## Expected behavior:
Upon usage, the Pixie Queen spawn egg in the offhand will get consumed, spawning the boss and without affecting the mainhand item.

## Server Log / Error Report
Unavailable

## Environment: 
FoxyMachines vDEV - 49 (git 7654621f)

 - Minecraft Version: Paper git-Paper-180 (MC: 1.17.1) Java 16
 - CS-CoreLib Version: None
 - Slimefun Version: Custom
 - Plugin Version: Unsure

**Comment by GallowsDove** [comment]
Should be fixed with 2ec1bb64b28fee7d1c2a6b7d076a7a21c5e92046
