### ISSUE TITLE
[ID Conflict] Blood

### ISSUE THREAD

**Issue by TheLittleCube** [GallowsDove/FoxyMachines#39]
Server startup error. Requested to post issue here.

Reproduce via loading up: 
FoxyMachines with BloodAlchemy 

[Pastebin](https://pastebin.com/XqVC6VFW)
[Full Log](https://pastebin.com/NXabi5ta) (Line 412)

Versions:
FoxyMachines vDEV - 50 (git **2c8f23a8)**
BloodAlchemy vALPHA

**Comment by GallowsDove** [comment]
Pretty sure that Riley should fix this since this addon and it's ID's existed way before blood alchemy

**Comment by TheLittleCube** [comment]
> Pretty sure that Riley should fix this since this addon and it's ID's existed way before blood alchemy

Don't know who that is.. your request via log was to post here.. I will attempt to find "Riley"
