### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by WongIong** [GallowsDove/FoxyMachines#47]
## Description (Required)
Player was holding a fill wand, then the server crashed.
It happened twice.

## Steps to reproduce the Issue (Required)
We have tried to reproduce, but we can't.

## Expected behavior (Required)
No crash.

## Server Log / Error Report
https://pastebin.com/QvL4xLMT

## Environment (Required)
![image](https://user-images.githubusercontent.com/36799194/153606592-3b504009-e725-415c-a86d-735f1a6e4001.png)
![image](https://user-images.githubusercontent.com/36799194/153606714-000e1f07-da76-4d70-a3fb-4bcdd12794be.png)

**Comment by Seggan** [comment]
Can we have the *full* server log?

**Comment by WongIong** [comment]
I could give you all logs about slimefun and foxy.
There are no error or something else before the crash.

**Comment by WongIong** [comment]
https://pastebin.com/GXiikfkZ

**Comment by WongIong** [comment]
It happens again

**Comment by GallowsDove** [comment]
I'm sorry but it just looks like it's an issue with your server not handling the load, I don't think it has anything to do with Foxy. If anyone has any more info, I'll gladly reopen this

**Comment by WongIong** [comment]
It was just a tiny scale to deal with
100blocks in total...
