### ISSUE TITLE
max-chunk-loaders doesn't works and Chunk Loader after breaking keeps the chunk loaded forever after server restart

### ISSUE THREAD

**Issue by SideLo98** [GallowsDove/FoxyMachines#49]
## Description (Required)

1st issue: "max-chunk-loaders: 8" option in config does not works we can still place 8+ chunk loaders.
2nd issue: Placing chunk loaders keeps the chunk force-loaded, breaking it reverts the chunk back to be NOT force-loaded which is fine, but now if we restart the server at this point next time server starts those chunks will be force-loaded without chunk loaders.

## Steps to reproduce the Issue (Required)

https://streamable.com/6oiosg

## Expected behavior (Required)

1st issue: max-chunk-loaders should only allow the number defined in config to be placed in-game per player.
2nd issue: once the chunk loaders are broken/removed from that chunk it should not keep that chunk loaded again after server restart.

## Server Log / Error Report

no errors
edit: read 2nd comment

## Environment (Required)

![image](https://user-images.githubusercontent.com/67060780/154899337-7b709c1c-63bd-44fc-bfdc-ae10bee2c343.png)

 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: -
 - Slimefun Version: DEV - 999
 - Plugin Version: DEV - 53

**Comment by SideLo98** [comment]
for some reason now I cannot reproduce the 2nd issue It was lucky that I recorded it. Maybe developer could find any issue idk ?

**Comment by SideLo98** [comment]
Not related to above I got this error today in console: https://pastebin.com/mdGZZSp6

**Comment by GallowsDove** [comment]
Unfortunately I'm also not able to reproduce this, so there is nothing for me to do. If anyone else encounter this. or if you encounter it again, please reply to this issue and I'll reopen it
