### ISSUE TITLE
Unbreakble Rune didn't work

### ISSUE THREAD

**Issue by huynhvu25** [GallowsDove/FoxyMachines#57]
## Description (Required)

The rune still on the ground with the item, and the item didn't become unbreakable (nothing happened)

## Steps to reproduce the Issue (Required)

Drop the rune and the item you want to make it unbreakable on the ground.

## Expected behavior (Required)

Item will become unbreakable after combining with the rune.

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version:
 - Slimefun Version: DEV - 1014 (git f431aa6d)
 - Plugin Version: DEV - 58 (git c2c2b8a7)

**Comment by JasperChaseTOQ** [comment]
what item did you try to use it on? and can you provide screenshots please?
