### ISSUE TITLE
axolotl

### ISSUE THREAD

**Issue by komodowaran** [GallowsDove/FoxyMachines#59]
## Description (Required)

The quest to kill axolotl does not end when killing a axolotl

## Steps to reproduce the Issue (Required)
- get quest to kill axelotl with /foxy quest
- kill some axolotl and see that u still have the same quest, and don't get any rewards

## Expected behavior (Required)
- i expected to get a cursed shard, and a new quest

## Environment (Required)
![version](https://user-images.githubusercontent.com/109506130/185945607-86b75023-a30e-4894-8623-5170d8823ea7.png)

**Comment by komodowaran** [comment]
This happens with the cursed and the Celestial sword.

I tested it with 4 different collors, and grown up as well as not grown up axolotl.
none seem to register the quest correctly.

**Comment by GallowsDove** [comment]
Could you please show me your /foxy quest? Axolotl isn't even added, so I don't really get how could you get it in a quest.

**Comment by komodowaran** [comment]
ok, seems the server messed with the addon
