### ISSUE TITLE
new blocks are not recognizable by the fill wand

### ISSUE THREAD

**Issue by RIPISDRAD** [GallowsDove/FoxyMachines#67]
## Description (Required)

new blocks are not recognizable by the fill wand

to fill it with the 1.19 blocks

I test it with tinted glass
not sure about the others

 - Minecraft Version: 1.19.4
![2023-05-08_00 42 00](https://user-images.githubusercontent.com/76468672/236700554-2e3ace03-f22c-4487-962d-b88c1306b7ad.png)

**Comment by ybw0014** [comment]
Tinted glass is added in 1.17. According to the code, the tinted glass is not an occluding block, nor in the whitelist, so it can't be a valid material for wand.
