### ISSUE TITLE
Not Enabling plugin

### ISSUE THREAD

**Issue by WongIong** [GallowsDove/FoxyMachines#71]
## Server Log / Error Report
https://pastebin.com/uasy9Adx

## Environment (Required)
Paper 1.17.1
Slimefun DEV1071
Foxy 64

**Comment by ubdeadhaha** [comment]
also have this issue. Paper 1.19.3-448, SF Dev 1072, Foxy 64, ProtocolLib 5.0.0

**Comment by DexterSK** [comment]
same purpur 1.20.1

**Comment by JustAHuman-xD** [comment]
Should be resolved as of #72
