### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by JaVlinPi** [GallowsDove/FoxyMachines#81]
## Description (Required)
When hooked up to a network, items can only be pushed in if there is already an item of that type in the input slot. This is an issue for the improvement forge as gear can not stack. Any stackable item will push in if there is already at least one in an input slot. 

## Steps to reproduce the Issue (Required)
Attach network pusher to improvement forge. Add any gear to pusher. Item does not push input improvement forge.

## Expected behavior (Required)
The item to be pushed into the improvement forge.

## Server Log / Error Report
N/A

## Environment (Required)
I am not the server admin so I cannot run /sf versions, but this addon was installed after the last update, so it should be the latest build.

**Comment by JustAHuman-xD** [comment]
This is intended behavior I’m pretty sure

**Comment by JustAHuman-xD** [comment]
As it was intentionally coded to do this
