### ISSUE TITLE
Boss projectiles not de-spawning.

### ISSUE THREAD

**Issue by SpyB0rg** [GallowsDove/FoxyMachines#83]
## Description (Required)
After spawning and fighting the Pixie Queen and/or Headless Horseman, the arrows that are fired by them, stay in the air indefinalty.

## Steps to reproduce the Issue (Required)
After defeating the Pixie Queen, or Headless Horseman, the projectiles stay in the air.

Attched a screenshot.
![foxy_machines_projectiles](https://github.com/GallowsDove/FoxyMachines/assets/78881993/31c7cc09-7e7e-4466-a6ee-cb217e1498ba)

## Expected behavior (Required)
I expected the Projectiles to de-spawn like vanilla arrows.

## Server Log / Error Report
No error report, just entities not de-spawning.

## Environment (Required)
[FoxyMachines] Enabling FoxyMachines vDEV - 67 (git 0028aa93)
![SF_Versions](https://github.com/GallowsDove/FoxyMachines/assets/78881993/9df7ef9e-fd2c-4eae-9dd6-1371206b08fe)

This server is running CraftBukkit version 4042-Spigot-c198da2-7e43f3b (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

[CMILib] Loading CMILib v1.4.4.3

Server version: v1_20_R3 - 1.20.4 - spigot

[15:47:11] [Server thread/INFO]: Plugins (25): EasyCleanup, PlaceholderAPI, UltimateTimber, CMILib, MyEasySpawn, NightVision, EnchantPlus, Vault, WorldEdit, Essentials, Randomtp, Multiverse-Core, Slimefun, EconomyShopGUI, PyroFishing, CoreProtect, AuraSkills, ExtraTools, FoxyMachines, SimpleMaterialGenerators, ExtraGear, InfinityExpansion, FluffyMachines, SimpleUtils, Networks

Thanks.

**Comment by GallowsDove** [comment]
@JustAHuman-xD was this fixed in #78 ? If so, it can be closed

**Comment by JustAHuman-xD** [comment]
> @JustAHuman-xD was this fixed in #78 ? If so, it can be closed

Should be yeah, any existing arrows will need to be removed by command but no more should be created
